### ISSUE TITLE
Variablen in Custumpages lassen sich per MQTT nicht ändern, wenn MQTT-Prefix ein "/" enthält.

### ISSUE THREAD

**Issue by Eulensammler** [Blueforcer/SmartPusher#3]
In Datei MqttManager.cpp in Zeile 137  in "    int firstSlash = strTopic.indexOf("/custompage/") + 1;"  ändern.  "/custumpage" fehlt !  Betrifft Beta 2.52.

**Comment by Blueforcer** [comment]
fixed for next version
